### ISSUE TITLE
Settings page doesn't have an action bar when using dark theme

### ISSUE THREAD

**Issue by alex-heritier** [bowenchin/RemindrApp-Android#1]
Switching to the dark theme removes the action bar from the settings screen. This persists even when backing out and re-entering the settings screen.

**Comment by bowenchin** [comment]
Hi @alex-heritier, thanks for raising this issue. This is a known issue of the dark theme and I will look into it.

**Comment by bowenchin** [comment]
@alex-heritier I have rebranded and updated the app. You may download it at https://play.google.com/store/apps/details?id=com.bowenchin.android.noter

Thanks for your support!
